### ISSUE TITLE
Color - design ready.

### ISSUE THREAD

**Issue by ChialiTsai** [vimwitch/uikit#2]
Please see https://www.figma.com/file/7u3sAaBofEgV4bZTLAP2YV?node-id=11:135#153704005

Just testing to open issue here. please take over for development, thank you.

**Comment by vimwitch** [comment]
It's too many colors to choose from? We need some specific shades to use.

**Comment by ChialiTsai** [comment]
mmm...maybe very basic, just black and white.
the other color spectrum, I think we do need it, because for other projects, they might use those color sets.

all colors are from the eth logo colored version, with shades.

**Comment by vimwitch** [comment]
So the idea is have all the color variations available in the kit?

**Comment by vimwitch** [comment]
Closing in favor of #11
